export interface Doctor {
  id: number;
  name: string;
  specialties: string[];
  experience: number;
  fee: number;
  consultationType: string;
  qualification?: string;
  clinicName?: string;
  location?: string;
  imageUrl?: string;
}

export const doctors: Doctor[] = [
  {
    id: 1,
    name: "Dr. Arun Kumar",
    specialties: ["Cardiology", "Internal Medicine"],
    experience: 15,
    fee: 1000,
    consultationType: "Video Consult",
    qualification: "MD, DM Cardiology",
    clinicName: "Heart Care Clinic",
    location: "Mumbai",
  },
  {
    id: 2,
    name: "Dr. Priya Sharma",
    specialties: ["Dermatology", "Cosmetology"],
    experience: 8,
    fee: 800,
    consultationType: "In Clinic",
    qualification: "MBBS, MD Dermatology",
    clinicName: "Skin & Beauty Clinic",
    location: "Delhi",
  },
  {
    id: 3,
    name: "Dr. Rajesh Patel",
    specialties: ["Orthopedics", "Sports Medicine"],
    experience: 12,
    fee: 900,
    consultationType: "Video Consult",
    qualification: "MS Orthopedics",
    clinicName: "Joint Care Center",
    location: "Bangalore",
  },
  {
    id: 4,
    name: "Dr. Meera Reddy",
    specialties: ["Pediatrics", "Neonatology"],
    experience: 10,
    fee: 700,
    consultationType: "In Clinic",
    qualification: "MD Pediatrics",
    clinicName: "Child Care Hospital",
    location: "Chennai",
  },
  {
    id: 5,
    name: "Dr. Suresh Iyer",
    specialties: ["Neurology", "Psychiatry"],
    experience: 20,
    fee: 1200,
    consultationType: "Video Consult",
    qualification: "MD, DM Neurology",
    clinicName: "Brain & Mind Care",
    location: "Hyderabad",
  },
  {
    id: 6,
    name: "Dr. Anjali Desai",
    specialties: ["Gynecology", "Obstetrics"],
    experience: 14,
    fee: 900,
    consultationType: "In Clinic",
    qualification: "MS Gynecology",
    clinicName: "Women's Health Center",
    location: "Pune",
  },
  {
    id: 7,
    name: "Dr. Vikram Singh",
    specialties: ["ENT", "Head and Neck Surgery"],
    experience: 9,
    fee: 800,
    consultationType: "Video Consult",
    qualification: "MS ENT",
    clinicName: "ENT Care Hospital",
    location: "Kolkata",
  },
  {
    id: 8,
    name: "Dr. Fatima Khan",
    specialties: ["Endocrinology", "Diabetology"],
    experience: 11,
    fee: 1000,
    consultationType: "In Clinic",
    qualification: "MD, DM Endocrinology",
    clinicName: "Diabetes Care Center",
    location: "Ahmedabad",
  },
  {
    id: 9,
    name: "Dr. John Matthew",
    specialties: ["Ophthalmology", "LASIK Surgery"],
    experience: 16,
    fee: 850,
    consultationType: "Video Consult",
    qualification: "MS Ophthalmology",
    clinicName: "Eye Care Institute",
    location: "Kochi",
  },
  {
    id: 10,
    name: "Dr. Sanjay Gupta",
    specialties: ["Gastroenterology", "Hepatology"],
    experience: 18,
    fee: 1100,
    consultationType: "In Clinic",
    qualification: "MD, DM Gastroenterology",
    clinicName: "Digestive Health Clinic",
    location: "Jaipur",
  },
];

export const allSpecialties = [
  "General Physician",
  "Dentist",
  "Dermatologist",
  "Paediatrician",
  "Gynaecologist",
  "ENT",
  "Diabetologist",
  "Cardiologist",
  "Physiotherapist",
  "Endocrinologist",
  "Orthopaedic",
  "Ophthalmologist",
  "Gastroenterologist",
  "Pulmonologist",
  "Psychiatrist",
  "Urologist",
  "Dietitian/Nutritionist",
  "Psychologist",
  "Sexologist",
  "Nephrologist",
  "Neurologist",
  "Oncologist",
  "Ayurveda",
  "Homeopath",
];
